### PR TITLE
Export parse function to JS

### PR DESCRIPTION
**Pull request by nothingisdead**
I changed entry.c to entry.cpp and modified the build process a bit to export Module.raw_parse with Embind. I also had to update to libpg_query 9.5-1.4.1 as I was running into an error in the `pg_query_exit_memory_context` function. I didn't look into it too far as 9.5-1.4.1 worked fine as-is.

Note that this changes the return format of the `Module.parse` function to map the C struct `PgQueryParseResult` directly to a JS object.

Thanks again for this library!

### CODE REVIEW

**Comment by jmealo** [comment]
@nothingisdead this is great, I was looking to export the entire error struct :-) :+1:

**Comment by lfittl** [comment]
Forgot to merge this, thanks @jmealo for commenting and the implicit reminder :)

**Comment by jmealo** [comment]
@lfittl: this still works well, but I did notice this:

```
stderr_buffer":"","error":{"message":"","funcname":"ÿ","filename":"\u0004","lineno":747221,"cursorpos":321760,"context":"NSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE"}}
```

(there's no error in the query and it parses fine, the AST looks good)

I think it's related to embind? (https://github.com/kripken/emscripten/issues/1194)

**Comment by lfittl** [comment]
@jmealo Investigating...

**Comment by lfittl** [comment]
@jmealo Should be fixed now - needed to add some additional protection against NULL pointers :)

**Comment by lfittl** [comment]
@jmealo FWIW, I've done a bit more cleanup - the library is now also correctly scoped as `PgQuery` and published on npm.

Have fun! 🎉

**Pull request merged**
