### PR TITLE
Upgrade to Postgres 13 parser / `pg_query_scan` support

### LINKED ISSUE #3: WASM build
With WASM now supported in Firefox and Chrome it would be good to see a WASM build. I spent a few hours trying to get it work, but had no luck when using the [trzeci/emscripten:sdk-tag-1.37.3-64bit](https://hub.docker.com/r/trzeci/emscripten/tags/) docker image.

### PR DESCRIPTION
**Pull request by PhilipTrauner**
I split the `Makefile` into a shell script (flattens the source) and `Makefile` (builds the source) combo because the semantics around build systems (required because `emscripten` doesn't allow the use of `-o` with multiple source files anymore) and phony targets are weird.

Compatibility with the Postgres 10 parser is retained, although `pg_query_scan` support is disabled.

Credit goes out to @neighbaa, who documented many of the changes necessary to make this work in #7.
Same caveat applies though, `EXPORT_ES6` implies / requires `MODULARIZE`.

Resolves #3, because `emscripten` embeds a WebAssembly blob *within* the `.js` file (base64 encoded).

### CODE REVIEW

**Comment by lfittl** [comment]
@PhilipTrauner Thanks for the contribution!

A few preliminary thoughts:

- Whilst I can see how the separate shell script makes it easier, the fact that one can't use `make`, but rather needs to call `build.sh` which then calls the Makefile, is a bit odd - is there a way we can either keep this in one Makefile, or have the Makefile call build.sh? (happy to look into this myself, if you'd like)

- Does this mean the build now requires WebAssembly support? That's not necessarily a problem (since nowadays that is available pretty universally), but it would be good to know.

- For the WebAssembly file, if I understand correctly this is now embedded into the output - I wonder if it wouldn't be better to keep it a separate file, since some people might prefer to ship this as a `.wasm` file instead of a base64-encoded `.js` file?

**Comment by PhilipTrauner** [comment]
> Whilst I can see how the separate shell script makes it easier, the fact that one can't use `make`, but rather needs to call `build.sh` which then calls the Makefile, is a bit odd - is there a way we can either keep this in one Makefile, or have the Makefile call build.sh? (happy to look into this myself, if you'd like)

I went with the second approach (as of [`628e69d4`](https://github.com/pganalyze/pg-query-emscripten/pull/8/commits/9b551774601e8fd16623ae833b000b3daeea2b4e)).

> Does this mean the build now requires WebAssembly support? That's not necessarily a problem (since nowadays that is available pretty universally), but it would be good to know.

As of [`212077e`](https://github.com/pganalyze/pg-query-emscripten/pull/8/commits/5390b9be794f8bd475cc7a2cef8ac15b6ad7e6a3) JavaScript with embedded WebAssembly is emitted by default. By setting `WASM=0` plain JavaScript is emitted instead. The plain JavaScript version is slightly larger.

> For the WebAssembly file, if I understand correctly this is now embedded into the output - I wonder if it wouldn't be better to keep it a separate file, since some people might prefer to ship this as a .wasm file instead of a base64-encoded `.js` file?

The default setting (`WASM=1` is implied if left unspecified) embeds the WebAssembly binary into the JavaScript artifact. I'm not aware (although I certainly wouldn't call myself experienced with Emscripten) of a way to change this behaviour.

**Comment by PhilipTrauner** [comment]
> Whilst I can see how the separate shell script makes it easier, the fact that one can't use make, but rather needs to call build.sh which then calls the Makefile, is a bit odd - is there a way we can either keep this in one Makefile, or have the Makefile call build.sh? (happy to look into this myself, if you'd like)

I can look into the first approach as well if you like 😇 (@lfittl)

**Comment by PhilipTrauner** [comment]
Sorry to keep pestering you @lfittl, but I'd appreciate if you could take another look at this.

**Comment by lfittl** [comment]
> Sorry to keep pestering you @lfittl, but I'd appreciate if you could take another look at this.

No worries - I think the main thing to change here would be how the Makefile and build.sh interact - I'm not a fan of the two-way calling. Can we avoid having `flatten.sh` call the Makefile?

**Comment by PhilipTrauner** [comment]
Sure, would a recursive `make` call be alright with you? 

```makefile
ARTIFACT := pg_query.js

.PHONY: flatten

all: flatten

flatten:
	# Flattening operations
    $(MAKE) $(ARTIFACT)

$(ARTIFACT):
    # Building of artifact
```

(edit: just went ahead and [did it](https://github.com/pganalyze/pg-query-emscripten/pull/8/commits/a40af299fbd1c1535fa4d83fe04db4dd105484ca))

**Comment by PhilipTrauner** [comment]
Is the recursive `make` approach close to what you had in mind (@lfittl)?

**Comment by PhilipTrauner** [comment]
Sorry for being a bit of a nuisance, but I'd really like to get this over the line @lfittl. Is there any outstanding work to be done from your perspective?

**Comment by kristiandupont** [comment]
Did this (PR | project) die? That would be sad to see..

**Comment by PhilipTrauner** [comment]
This fork ended up significantly diverging from `master`, therefor I'm not sure if merging is desirable at this point. 
That being said, the fork did accomplish what it set out to do (parser upgrade / `pg_query_scan` support), so if those features are deemed necessary, one can just use the fork.

**Comment by lfittl** [comment]
My apologies for not getting back to this a few years ago, and thanks for maintaining the fork!

Since the fork itself now has gotten outdated, and someone was interested in using this project recently, I figured we can merge this (done via #9) and update to Postgres 16. Since your work is merged now via that separate PR and released as 5.1.0 (matching libpg_query versioning), I'll close this one here.

**Pull request closed without merging**
