### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by EliSnow**
Added optimization level 3 to the `emcc` command.
Upped optimization level from 2 to 3 on the `em++` command.
Added `--closure 1` to the `em++` command.

These changes take the built js from 3.1MB to 2.7MB, and with the higher optimization level should increase performance.

### CODE REVIEW

**Comment by EliSnow** [comment]
@lfittl, would you like me to include the newly built pg_query.js with this PR?

**Comment by lfittl** [comment]
@EliSnow Yeah, that'd be helpful - makes it easier to try it out :)

**Comment by EliSnow** [comment]
@lfittl, in case you haven't seen it, the built pg_query.js is now included in this PR.

**Comment by lfittl** [comment]
@EliSnow I did see it, but needed to test still if this was working with my example as expected. I'll probably get to it sometime this weekend :)

**Comment by EliSnow** [comment]
@lfittl, any update?

**Comment by lfittl** [comment]
@EliSnow Merged with modifications, since the closure compiler broke things unfortunately.

**Pull request closed without merging**
