### PR TITLE
update to latest libpg_query (10-1.0.1)

### PR DESCRIPTION
**Pull request by shamrin**
* update `LIB_PG_QUERY_TAG`
* fix compilation
* update compiled `pg_query.js` (now weights 2.2M, built with Emscripten 1.38.0)

### CODE REVIEW

**Comment by shamrin** [comment]
@lfittl Could you check it out please?

**Comment by lfittl** [comment]
@shamrin Apologies, I missed this - taking a look at this now.

**Comment by lfittl** [comment]
@shamrin I ended up redoing this locally, to make sure I could reproduce the build. Committed as https://github.com/lfittl/pg-query-emscripten/commit/9b2d0e405ee774c4d06021783a1e67c515b8ac17 and released as 0.1.0 on npm.

Note that I had to disable WebAssembly support for now (which is now enabled by default in emscripten), since I otherwise kept running into errors when actually trying to use the library.

Thanks for your contribution!

**Comment by shamrin** [comment]
@lfittl Thank you for your work on this awesome library!

**Pull request closed without merging**
