### PR TITLE
Fixes lfittl/pg-query-emscripten#4

### PR DESCRIPTION
**Pull request by EliSnow**

### CODE REVIEW

**Comment by lfittl** [comment]
Nice - thanks for digging into it!

**Comment by EliSnow** [comment]
Thanks @lfittl for merging this in so quickly. Will you push a version update to npm?

**Comment by lfittl** [comment]
@EliSnow Its on my list - hopefully today, but might be a bit later this week.

**Comment by lfittl** [comment]
@EliSnow Now released as 0.0.4 - thanks for fixing this :)

**Pull request merged**
